import "script!jquery/dist/jquery.min";
import "angular";
import "angular-resource";
import "angular-animate";
import "angular-local-storage";
import "angular-ui-bootstrap";
import "angular-md5/angular-md5";
import "bootstrap/dist/js/bootstrap.min.js";
import "font-awesome/css/font-awesome.css";
